import { SeasonProfile, SeasonId } from "./types";

export const SEASONS_DATA: Record<SeasonId, SeasonProfile> = {
  light_spring: {
    id: "light_spring",
    name: "Light Spring",
    family: "Spring",
    dimensions: { value: "Light", contrast: "Low", undertone: "Warm-Neutral", chroma: "Bright" },
    sisterSeasonId: "light_summer",
    bestColorsDescription: ["Baby Pink", "Mint Green", "Soft Peach", "Sky Blue"],
    avoidColorsDescription: ["Mustard", "Rust", "Olive Green", "Black"],
  },
  warm_spring: {
    id: "warm_spring",
    name: "Warm Spring",
    family: "Spring",
    dimensions: {
      value: "Light-to-Medium",
      contrast: "Medium",
      undertone: "Warm",
      chroma: "Bright",
    },
    sisterSeasonId: "warm_autumn",
    bestColorsDescription: ["Warm Coral", "Golden Yellow", "Apricot", "Bright Teal"],
    avoidColorsDescription: ["Magenta", "Cool Lavender", "Pure White", "Icy Blue"],
  },
  true_spring: {
    id: "true_spring",
    name: "True Spring",
    family: "Spring",
    dimensions: { value: "Medium", contrast: "Medium-High", undertone: "Warm", chroma: "Bright" },
    sisterSeasonId: "true_autumn",
    bestColorsDescription: ["Bright Orange", "Marigold", "Lime Green", "Clear Red"],
    avoidColorsDescription: ["Dusty Mauve", "Slate Grey", "Navy Blue", "Pastel Pink"],
  },
  bright_spring: {
    id: "bright_spring",
    name: "Bright Spring",
    family: "Spring",
    dimensions: {
      value: "Medium-to-Deep",
      contrast: "High",
      undertone: "Warm-Neutral",
      chroma: "Bright",
    },
    sisterSeasonId: "bright_winter",
    bestColorsDescription: ["Coral", "Bright Turquoise", "Sea Green", "Vivid Yellow"],
    avoidColorsDescription: ["Pastel Grey", "Dusty Brown", "Cool Grey"],
  },

  light_summer: {
    id: "light_summer",
    name: "Light Summer",
    family: "Summer",
    dimensions: { value: "Light", contrast: "Low", undertone: "Cool-Neutral", chroma: "Soft" },
    sisterSeasonId: "light_spring",
    bestColorsDescription: ["Lavender", "Powder Blue", "Rose Pink", "Light Grey"],
    avoidColorsDescription: ["Mustard", "Dark Brown", "Black", "Deep Rust"],
  },
  cool_summer: {
    id: "cool_summer",
    name: "Cool Summer",
    family: "Summer",
    dimensions: { value: "Light-to-Medium", contrast: "Medium", undertone: "Cool", chroma: "Soft" },
    sisterSeasonId: "cool_winter",
    bestColorsDescription: ["Periwinkle", "Soft Fuchsia", "Slate Blue", "Jade Green"],
    avoidColorsDescription: ["Terracotta", "Neon Orange", "Golden Beige", "Electric Yellow"],
  },
  true_summer: {
    id: "true_summer",
    name: "True Summer",
    family: "Summer",
    dimensions: { value: "Medium", contrast: "Medium", undertone: "Cool", chroma: "Soft" },
    sisterSeasonId: "true_winter",
    bestColorsDescription: ["Pigeon Blue", "Muted Raspberry", "Soft Sage", "Mauve"],
    avoidColorsDescription: ["Mustard", "Orange", "Cream", "Warm Brown"],
  },
  soft_summer: {
    id: "soft_summer",
    name: "Soft Summer",
    family: "Summer",
    dimensions: {
      value: "Medium-to-Deep",
      contrast: "Low",
      undertone: "Cool-Neutral",
      chroma: "Soft",
    },
    sisterSeasonId: "soft_autumn",
    bestColorsDescription: ["Muted Plum", "Slate Grey", "Soft Rose", "Charcoal"],
    avoidColorsDescription: ["Neon Orange", "Bright Yellow", "Vivid Coral"],
  },

  soft_autumn: {
    id: "soft_autumn",
    name: "Soft Autumn",
    family: "Autumn",
    dimensions: {
      value: "Light-to-Medium",
      contrast: "Low",
      undertone: "Warm-Neutral",
      chroma: "Soft",
    },
    sisterSeasonId: "soft_summer",
    bestColorsDescription: ["Olive Green", "Beige", "Warm Pink", "Terracotta"],
    avoidColorsDescription: ["Magenta", "Royal Blue", "Pure White"],
  },
  warm_autumn: {
    id: "warm_autumn",
    name: "Warm Autumn",
    family: "Autumn",
    dimensions: { value: "Medium", contrast: "Medium", undertone: "Warm", chroma: "Soft" },
    sisterSeasonId: "warm_spring",
    bestColorsDescription: ["Pumpkin Orange", "Rich Amber", "Moss Green", "Camel"],
    avoidColorsDescription: ["Icy Pink", "Pure Black", "Fuchsia", "Cobalt Blue"],
  },
  true_autumn: {
    id: "true_autumn",
    name: "True Autumn",
    family: "Autumn",
    dimensions: {
      value: "Medium-to-Deep",
      contrast: "Medium-High",
      undertone: "Warm",
      chroma: "Soft",
    },
    sisterSeasonId: "true_spring",
    bestColorsDescription: ["Rust", "Deep Olive", "Burnt Orange", "Teal Blue"],
    avoidColorsDescription: ["Hot Pink", "Ice Blue", "Pure White", "Neon Green"],
  },
  deep_autumn: {
    id: "deep_autumn",
    name: "Deep Autumn",
    family: "Autumn",
    dimensions: { value: "Deep", contrast: "High", undertone: "Warm-Neutral", chroma: "Soft" },
    sisterSeasonId: "deep_winter",
    bestColorsDescription: ["Burgundy", "Deep Forest Green", "Dark Chocolate", "Mustard"],
    avoidColorsDescription: ["Pastel Pink", "Baby Blue", "Lavender"],
  },

  bright_winter: {
    id: "bright_winter",
    name: "Bright Winter",
    family: "Winter",
    dimensions: {
      value: "Light-to-Medium",
      contrast: "High",
      undertone: "Cool-Neutral",
      chroma: "Bright",
    },
    sisterSeasonId: "bright_spring",
    bestColorsDescription: ["Royal Blue", "Fuchsia", "Bright Teal", "Pure White"],
    avoidColorsDescription: ["Beige", "Dusty Rose", "Mint Green (Light)"],
  },
  cool_winter: {
    id: "cool_winter",
    name: "Cool Winter",
    family: "Winter",
    dimensions: { value: "Medium", contrast: "High", undertone: "Cool", chroma: "Bright" },
    sisterSeasonId: "cool_summer",
    bestColorsDescription: ["Emerald Green", "Sapphire Blue", "True Violet", "Magenta"],
    avoidColorsDescription: ["Peach", "Orange", "Gold", "Warm Brown"],
  },
  true_winter: {
    id: "true_winter",
    name: "True Winter",
    family: "Winter",
    dimensions: { value: "Medium-to-Deep", contrast: "High", undertone: "Cool", chroma: "Bright" },
    sisterSeasonId: "true_summer",
    bestColorsDescription: ["Electric Blue", "Shocking Pink", "Pure Crimson", "Stark Black"],
    avoidColorsDescription: ["Camel", "Mustard", "Terracotta", "Olive"],
  },
  deep_winter: {
    id: "deep_winter",
    name: "Deep Winter",
    family: "Winter",
    dimensions: { value: "Deep", contrast: "Very-High", undertone: "Cool", chroma: "Bright" },
    sisterSeasonId: "deep_autumn",
    bestColorsDescription: ["Navy Blue", "Deep Emerald", "True Burgundy", "Pure Black"],
    avoidColorsDescription: ["Pastel Yellow", "Camel", "Peach"],
  },
};
